### ISSUE TITLE
Duplicate key - ha-card-border-radius

### ISSUE THREAD

**Issue by milperks** [estiens/sweet_pink_hass_theme#5]
Firstly, thanks I love this theme!

From my logs:

Logger: homeassistant.util.yaml.loader
Source: util/yaml/loader.py:500
First occurred: 21 October 2024 at 11:32:36 (5 occurrences)
Last logged: 08:58:48

YAML file /config/themes/sweetpink/sweetpink.yaml contains duplicate key "ha-card-border-radius". Check lines 27 and 122

**Comment by estiens** [comment]
will check and fixup!
