### ISSUE TITLE
Dropdown in automation unreadable when selected

### ISSUE THREAD

**Issue by milperks** [estiens/sweet_pink_hass_theme#6]
When expanding a section, the header text and background are all white which makes it unreadable. This is most obvious when editing automations in the UI:

![image](https://github.com/user-attachments/assets/1612b115-3f73-4d4d-aea0-8c7c21c72340)

**Comment by milperks** [comment]
I found the right class - input-fill-color

Created #7, very new to github so hope this is correct!

**Comment by estiens** [comment]
thank you so much for fixing this! sorry I missed it in github notifications - just got a new github account for a new job so havent been as on top of notifications over here

**Comment by estiens** [comment]
👍 merged and released
